# Generated by Django 6.0.7 on 2026-08-12 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_remove_user_niveau_etudes_user_niveau_etudes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('lieu', models.CharField(max_length=64, verbose_name='Lieu')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_comme_eleve', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.sujet', verbose_name='Matière')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_comme_prof', to=settings.AUTH_USER_MODEL, verbose_name='Répetiteur')),
            ],
        ),
    ]
