# Generated by Django 6.0.7 on 2026-08-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandelecon',
            name='status',
        ),
        migrations.AddField(
            model_name='demandelecon',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
