# Generated by Django 6.0.7 on 2026-09-30 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_demandelecon_status_demandelecon_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandelecon',
            name='heure',
        ),
        migrations.AddField(
            model_name='demandelecon',
            name='heure_debut',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Heure de début'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandelecon',
            name='heure_fin',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Heure de fin'),
            preserve_default=False,
        ),
    ]
