# Generated by Django 5.2.13 on 2026-06-18 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tariff',
        ),
        migrations.AddField(
            model_name='user',
            name='possible_eleve',
            field=models.BooleanField(default=False, verbose_name='À besoin de cours'),
        ),
        migrations.AddField(
            model_name='user',
            name='possible_prof',
            field=models.BooleanField(default=False, verbose_name='Peu donner des cours'),
        ),
        migrations.AddField(
            model_name='user',
            name='sujets_eleve',
            field=models.CharField(blank=True, choices=[('francais', 'Français'), ('anglais', 'Anglais'), ('allemand', 'Allemand'), ('maths', 'Mathématiques'), ('physique', 'Physique'), ('éco', 'Économie'), ('chimie', 'Chimie'), ('bio', 'Biologie'), ('philo', 'Philosophie'), ('psyco', 'Psycologie'), ('musique', 'Musique'), ('art', 'Arts visuels')], verbose_name='Matières'),
        ),
        migrations.AddField(
            model_name='user',
            name='sujets_prof',
            field=models.CharField(blank=True, choices=[('francais', 'Français'), ('anglais', 'Anglais'), ('allemand', 'Allemand'), ('maths', 'Mathématiques'), ('physique', 'Physique'), ('éco', 'Économie'), ('chimie', 'Chimie'), ('bio', 'Biologie'), ('philo', 'Philosophie'), ('psyco', 'Psycologie'), ('musique', 'Musique'), ('art', 'Arts visuels')], verbose_name='Matières'),
        ),
        migrations.AddField(
            model_name='user',
            name='tarif',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Tariff à l'heure"),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.CharField(max_length=100, verbose_name="Lieu d'habitation"),
        ),
    ]
