# Generated by Django 6.0.7 on 2026-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role_remove_user_tariff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='possible_prof',
            new_name='est_prof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='possible_eleve',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sujets_eleve',
        ),
        migrations.AlterField(
            model_name='user',
            name='sujets_prof',
            field=models.CharField(blank=True, choices=[('francais', 'Français'), ('anglais', 'Anglais'), ('allemand', 'Allemand'), ('maths', 'Mathématiques'), ('physique', 'Physique'), ('eco', 'Économie'), ('chimie', 'Chimie'), ('bio', 'Biologie'), ('philo', 'Philosophie'), ('psyco', 'Psycologie'), ('musique', 'Musique'), ('art', 'Arts visuels')], verbose_name='Matières'),
        ),
    ]
