# Generated by Django 6.0.7 on 2026-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_possible_prof_user_est_prof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du sujet')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='sujets_prof',
        ),
        migrations.AddField(
            model_name='user',
            name='sujets_prof',
            field=models.ManyToManyField(blank=True, to='authentication.sujet', verbose_name='Sujets enseignés'),
        ),
    ]
