# Generated by Django 6.0.7 on 2026-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_sujet_remove_user_sujets_prof_user_sujets_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='est_prof',
            field=models.BooleanField(default=False, verbose_name='Peut donner des cours'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sujets_prof',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.sujet', verbose_name='Sujets enseignés'),
        ),
    ]
