# Generated by Django 6.0.7 on 2026-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_est_prof_alter_user_sujets_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sujets_prof',
            field=models.ManyToManyField(blank=True, to='authentication.sujet', verbose_name='Sujets enseignés'),
        ),
    ]
