# Generated by Django 6.0.7 on 2026-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_sujets_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauEtudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Niveau d'études")),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='photo_de_profil',
        ),
        migrations.AddField(
            model_name='user',
            name='bibliographie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bibliographie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.CharField(max_length=20, verbose_name="Lieu d'habitation"),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_etudes',
            field=models.ManyToManyField(blank=True, to='authentication.niveauetudes', verbose_name="Niveau d'études"),
        ),
    ]
