# Generated by Django 6.0.7 on 2026-08-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_niveauetudes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='niveau_etudes',
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_etudes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.niveauetudes', verbose_name="Niveau d'études"),
        ),
    ]
